<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-AAKS8C7V" ignored="0" name="RetryMultipleFailedTestCases" tests="9" failures="2" timestamp="2023-05-07T23:18:32 IST" time="0.432" errors="0">
  <testcase name="Test1" time="0.094" classname="com.TestNgBasics.RetryTests1">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.004" classname="com.TestNgBasics.RetryTests1">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.003" classname="com.TestNgBasics.RetryTests1">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.003" classname="com.TestNgBasics.RetryTests1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.TestNgBasics.RetryTests1.Test1(RetryTests1.java:13)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.003" classname="com.TestNgBasics.RetryTests1">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.003" classname="com.TestNgBasics.RetryTests1">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.003" classname="com.TestNgBasics.RetryTests1">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.003" classname="com.TestNgBasics.RetryTests1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.TestNgBasics.RetryTests1.Test2(RetryTests1.java:19)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.003" classname="com.TestNgBasics.RetryTests1"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
